### ISSUE TITLE
No proper documentation provided.

### ISSUE THREAD

**Issue by abdulmanan7** [solutosoft/yii2-kendoui#2]
how can you publish code for reusability if you don't have documentation on how to use it.

very poor programming.

**Comment by leandrogehlen** [comment]
Don't use. Do your self.
Why do you is interested by a poor programming

**Comment by abdulmanan7** [comment]
what do you think ! i use your code huh coming on man !! no one will be able to use this code 
"Why do you is interested by a poor programming"
i was interested. not now just want to suggest you to write documentation so that no other like me waste time by your code.
i did my self by importing js lib at the top and write custom jquery and its working like charm.

one last question why you wrote this code ??

**Comment by leandrogehlen** [comment]
Why this man? you don't help this way.
